spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:8889/joindb
    username: root
    password: root
    
mybatis:
  configuration:
   log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
   map-underscore-to-camel-case: true
  mapper-locations: classpath:/com/join/mapper/*.xml
  
logging:
  level:
   org.springframework.jdbc.support.JdbcTransactionManager: debug
   
